package model.pojos;
// Generated 22/11/2012 12:12:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable, Comparable<Cancion> {


     private Integer idCancion;
     private String nombre;
     private String artista;
     private String pais;
     private Integer ano;
     private String ruta;
     private Set generoCancions = new HashSet(0);
     private Set historias = new HashSet(0);

    public Cancion() {
    }

    public Cancion(String nombre, String artista, String pais, Integer ano, String ruta, Set generoCancions, Set historias) {
       this.nombre = nombre;
       this.artista = artista;
       this.pais = pais;
       this.ano = ano;
       this.ruta = ruta;
       this.generoCancions = generoCancions;
       this.historias = historias;
    }
   
    public Integer getIdCancion() {
        return this.idCancion;
    }
    
    public void setIdCancion(Integer idCancion) {
        this.idCancion = idCancion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getArtista() {
        return this.artista;
    }
    
    public void setArtista(String artista) {
        this.artista = artista;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Set getGeneroCancions() {
        return this.generoCancions;
    }
    
    public void setGeneroCancions(Set generoCancions) {
        this.generoCancions = generoCancions;
    }
    public Set getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Set historias) {
        this.historias = historias;
    }


    /**
     * metodo que nos regresa el vector de valores de acuerdo a los generos existentes
     * @return 
     */
    public GeneroCancion getGeneroCancion(){
        return (GeneroCancion) getGeneroCancions().iterator().next();
    }

    public String toString(){
        return nombre+"-"+artista;
    }

    @Override
    public int compareTo(Cancion o) {
        return o.nombre.compareTo(this.nombre);
    }
    
}


