package model.pojos;
// Generated 22/11/2012 12:12:03 AM by Hibernate Tools 3.2.1.GA

import java.lang.reflect.Method;
import java.util.List;
import util.Espejo;




/**
 * GeneroCancion generated by hbm2java
 */
public class GeneroCancion  implements java.io.Serializable {


     private int idCancion;
     private Cancion cancion;
     private Double rock;
     private Double pop;
     private Double reggae;
     private Double reggaeton;
     private Double merengue;
     private Double salsa;
     private Double cumbia;
     private Double clasica;
     private Double jazz;
     private Double metal;
     private Double samba;
     private Double disco;

    public GeneroCancion() {
    }

	
    public GeneroCancion(int idCancion, Cancion cancion) {
        this.idCancion = idCancion;
        this.cancion = cancion;
    }
    public GeneroCancion(int idCancion, Cancion cancion, Double rock, Double pop, Double reggae, Double reggaeton, Double merengue, Double salsa, Double cumbia, Double clasica, Double jazz, Double metal, Double samba, Double disco) {
       this.idCancion = idCancion;
       this.cancion = cancion;
       this.rock = rock;
       this.pop = pop;
       this.reggae = reggae;
       this.reggaeton = reggaeton;
       this.merengue = merengue;
       this.salsa = salsa;
       this.cumbia = cumbia;
       this.clasica = clasica;
       this.jazz = jazz;
       this.metal = metal;
       this.samba = samba;
       this.disco = disco;
    }
   
    public int getIdCancion() {
        return this.idCancion;
    }
    
    public void setIdCancion(int idCancion) {
        this.idCancion = idCancion;
    }
    public Cancion getCancion() {
        return this.cancion;
    }
    
    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }
    public Double getRock() {
        return this.rock;
    }
    
    public void setRock(Double rock) {
        this.rock = rock;
    }
    public Double getPop() {
        return this.pop;
    }
    
    public void setPop(Double pop) {
        this.pop = pop;
    }
    public Double getReggae() {
        return this.reggae;
    }
    
    public void setReggae(Double reggae) {
        this.reggae = reggae;
    }
    public Double getReggaeton() {
        return this.reggaeton;
    }
    
    public void setReggaeton(Double reggaeton) {
        this.reggaeton = reggaeton;
    }
    public Double getMerengue() {
        return this.merengue;
    }
    
    public void setMerengue(Double merengue) {
        this.merengue = merengue;
    }
    public Double getSalsa() {
        return this.salsa;
    }
    
    public void setSalsa(Double salsa) {
        this.salsa = salsa;
    }
    public Double getCumbia() {
        return this.cumbia;
    }
    
    public void setCumbia(Double cumbia) {
        this.cumbia = cumbia;
    }
    public Double getClasica() {
        return this.clasica;
    }
    
    public void setClasica(Double clasica) {
        this.clasica = clasica;
    }
    public Double getJazz() {
        return this.jazz;
    }
    
    public void setJazz(Double jazz) {
        this.jazz = jazz;
    }
    public Double getMetal() {
        return this.metal;
    }
    
    public void setMetal(Double metal) {
        this.metal = metal;
    }
    public Double getSamba() {
        return this.samba;
    }
    
    public void setSamba(Double samba) {
        this.samba = samba;
    }
    public Double getDisco() {
        return this.disco;
    }
    
    public void setDisco(Double disco) {
        this.disco = disco;
    }


    public GeneroCancion sum(GeneroCancion genCan){
        GeneroCancion gen=new GeneroCancion();
        List<Method> getters = Espejo.obtenerGetters(GeneroCancion.class);
        for(Method method:getters){
            if(method.getReturnType().equals(Double.class)){
                Method setter=Espejo.getMethod(GeneroCancion.class,"set"+method.getName().substring(3,method.getName().length()));
                Espejo.invocaSet(setter,gen,(Double)Espejo.invocaGet(this,method) + (Double) Espejo.invocaGet(genCan,method));
            }
        }
        return gen;
    }

}


