package model.pojos;
// Generated 22/11/2012 12:12:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Historia generated by hbm2java
 */
public class Historia  implements java.io.Serializable, Comparable<Historia> {


     private Integer idHistoria;
     private Usuario usuario;
     private Cancion cancion;
     private Date fecha;

    public Historia() {
    }

    public Historia(Usuario usuario, Cancion cancion, Date fecha) {
       this.usuario = usuario;
       this.cancion = cancion;
       this.fecha = fecha;
    }
   
    public Integer getIdHistoria() {
        return this.idHistoria;
    }
    
    public void setIdHistoria(Integer idHistoria) {
        this.idHistoria = idHistoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Cancion getCancion() {
        return this.cancion;
    }
    
    public void setCancion(Cancion cancion) {
        this.cancion = cancion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @Override
    public int compareTo(Historia o) {
        return o.idHistoria.compareTo(this.idHistoria);
    }




}


