package model.pojos;
// Generated 22/11/2012 12:12:03 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String usuario;
     private String password;
     private Set generoUsuarios = new HashSet(0);
     private Set historias = new HashSet(0);

    public Usuario() {
    }

    public Usuario(String nombre, String usuario, String password, Set generoUsuarios, Set historias) {
       this.nombre = nombre;
       this.usuario = usuario;
       this.password = password;
       this.generoUsuarios = generoUsuarios;
       this.historias = historias;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getGeneroUsuarios() {
        return this.generoUsuarios;
    }
    
    public void setGeneroUsuarios(Set generoUsuarios) {
        this.generoUsuarios = generoUsuarios;
    }
    public Set getHistorias() {
        return this.historias;
    }
    
    public void setHistorias(Set historias) {
        this.historias = historias;
    }


    /**
     * metodo que nos da el vector de preferencias del usuario
     * @return 
     */
    public GeneroUsuario getGeneroUsuario(){
        return (GeneroUsuario) getGeneroUsuarios().iterator().next();
    }


    public String toString(){
        return nombre;
    }
}


